name: Aggregator BDD tests

on:
  push:
    # branches: ["master"]
  pull_request:

jobs:
  aggregator-bdd:
    name: BDD tests
    uses: joselsegura/processing-tools/.github/workflows/bdd.yaml@bdd-notification-service
    with:
      service: aggregator
      use_kafka: true
      use_postgres: true

  dvo-bdd:
    name: DVO BDD tests
    uses: joselsegura/processing-tools/.github/workflows/bdd.yaml@bdd-notification-service
    with:
      service: dvo-writer
      use_kafka: true
      use_postgres: true
