name: Go tests

on:
  push:
    # branches: [main, master]
  pull_request:

jobs:
  gotests:
    uses: joselsegura/processing-tools/.github/workflows/gotests.yaml@gotests_reusable_workflow
    with:
      use_postgres: true
