name: Go linters

on:
  push:
    # branches: ["master", "main"]
  pull_request:

jobs:
  golinters:
    permissions:
      contents: read
      pull-requests: write

    name: Go Linters
    uses: joselsegura/processing-tools/.github/workflows/golinters.yaml@go_linters
    with:
      abcgo_threshold: 55
